-- MySQL Workbench Synchronization
-- Generated: 2023-02-14 10:19
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: cristina

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `agencia3SI` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `agencia3SI`.`CLIENTE` (
  `idCLIENTE` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(45) NULL DEFAULT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `agencia3SI`.`CONTA` (
  `idCONTA` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Salário', 'Corrente', 'Poupança') NOT NULL,
  `saldo` FLOAT(11) NOT NULL,
  `senha` CHAR(8) NOT NULL,
  PRIMARY KEY (`idCONTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `agencia3SI`.`CONTAVINCULADA` (
  `CONTA_idCONTA` INT(11) NOT NULL,
  `CLIENTE_idCLIENTE` INT(11) NOT NULL,
  `dataAbertura` DATE NOT NULL,
  PRIMARY KEY (`CONTA_idCONTA`, `CLIENTE_idCLIENTE`),
  INDEX `fk_CONTA_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC),
  INDEX `fk_CONTA_has_CLIENTE_CONTA_idx` (`CONTA_idCONTA` ASC),
  CONSTRAINT `fk_CONTA_has_CLIENTE_CONTA`
    FOREIGN KEY (`CONTA_idCONTA`)
    REFERENCES `agencia3SI`.`CONTA` (`idCONTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTA_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `agencia3SI`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
